### ISSUE TITLE
您好，和我聊聊吧！

### ISSUE THREAD

**Issue by kalasoo** [kalasoo/kalasoo.github.io#1]
谢谢你访问我的主页，留下你的脚印吧

**Comment by shifuchen** [comment]
最近在考虑给自己的博客改版，寻找灵感时无意间打开了你的主页。新的设计很有禅意，令我感到惊喜。同时令我感到惊喜的还有掘金的改版。虽然我不是稀土的员工，但每一次看到稀土成长我都会很开心。愿你生活顺心，事业有成！

**Comment by kalasoo** [comment]
@shifuchen 谢谢，这个版本的网站满满开发了两个晚上，也希望有机会你可以来公司一起帮忙

**Comment by lishuo9527** [comment]
博客别树一帜，第一眼看到的时候，有种想把显示器竖起来的冲动。赞一个~

**Comment by kalasoo** [comment]
@lishuo9527 哈哈，我特别喜欢竖版排版觉得这才是中文应该的排版方式

**Comment by shuibaco** [comment]
本来以为是博文列表，仔细看了以后才发现是人生历程，给我很大的启发！不过说实话，竖排版+繁体字看得很不习惯，所以看得很慢。但是很慢也有很慢的好处哈哈。

**Comment by kalasoo** [comment]
@shuibaco 哈哈，谢谢。我大学在香港读的书，那时候图书馆里的书都是竖版的，因而主动学习了

**Comment by ChangBaiMonster** [comment]
很好看~

**Comment by kalasoo** [comment]
@ChangBaiMonster 谢谢，你也很棒！

**Comment by Dog-Lee** [comment]
脖子有点酸。

**Comment by elina1201** [comment]
膜拜大牛

**Comment by kalasoo** [comment]
@Dog-Lee 在想写一个新的，`Grid-based`

**Comment by kalasoo** [comment]
@elina1201 大佬您好

**Comment by Huangtuzhi** [comment]
以前的博客文章看不到了，有点可惜。

**Comment by kalasoo** [comment]
@Huangtuzhi 我也很可惜呢，现在您可以看我掘金上的内容： https://juejin.im/user/551d677ee4b0cd5b623f49cb

**Comment by kalasoo** [comment]
@lj0812 Hello, 很高兴认识您！

**Comment by johonz** [comment]
很有禅意的博客，很有新意！不过，“微软加速器第十期”这个链接是否有问题？

**Comment by kalasoo** [comment]
@johonz 我看一下

**Comment by xuexb** [comment]
666

**Comment by Molunerfinn** [comment]
HTTPS证书出问题啦

**Comment by pengliheng** [comment]
很棒的一家公司

**Comment by kalasoo** [comment]
@pengliheng 谢谢亲！

**Comment by Rain120** [comment]
博客很有个性，就是别着头看有点难受，我觉得明明老哥可以设计一根主线，每一页都是一年的成就或者这一年发生最有意义的事，然后滑动后，这根线能唯一到下一年，或者向前移，回到前一年，不知道大佬觉得这个想法怎么样

**Comment by kalasoo** [comment]
@Rain120 不错！

**Comment by Rain120** [comment]
@kalasoo 有种像碟中谍4还是5的开场，那种模式，由主线进入该年可以记录的事，希望有机会看到这种模式的博客

**Comment by Rain120** [comment]
@kalasoo 明白，最近掘金好像有很多新栏目以及讲坛类似的，大佬确实比较忙

**Comment by kalasoo** [comment]
@Rain120 是啊，最近干的事情挺多的

**Comment by Rain120** [comment]
@kalasoo 看到大佬最近来回奔波，忙得一匹，赞赞赞

**Comment by kalasoo** [comment]
@Rain120 还有很多事情想做，掘金离最终的目标距离还很远

**Comment by Rain120** [comment]
@kalasoo 坐等掘金越来越好，干巴爹

**Comment by kalasoo** [comment]
@Rain120 一起加油，笔芯

**Comment by hq5544** [comment]
加油

**Comment by N0TA11** [comment]
blog 的禅意以及“和我聊聊”的创意
都好酷～

**Comment by kalasoo** [comment]
@N0TA11 谢谢您！

**Comment by ChungZH** [comment]
NB！好有趣的创意，太厉害了 👍👍👍

**Comment by kalasoo** [comment]
@ChungZH 谢谢

**Comment by smileyby** [comment]
有一种武林秘籍的感觉，棒棒哒

**Comment by kalasoo** [comment]
@smileyby 嘿 - 哈 - 嘿 - 哈
